jarsigner -keystore Security.store ../lib/util/commons-logging-1.1.1.jar Security
jarsigner -keystore Security.store ../lib/util/dom4j-1.6.1.jar Security
jarsigner -keystore Security.store ../lib/util/http-client-4.0.1.jar Security
jarsigner -keystore Security.store ../lib/util/http-core-4.0.1.jar Security
jarsigner -keystore Security.store ../lib/util/json.jar Security
jarsigner -keystore Security.store ../lib/util/log4j-1.2.16.jar Security
jarsigner -keystore Security.store ../lib/util/poi-3.6-20091214.jar Security
jarsigner -keystore Security.store ../lib/util/proxool-0.9.1.jar Security
jarsigner -keystore Security.store ../lib/util/proxool-cglib.jar Security
jarsigner -keystore Security.store ../lib/util/quartz-all-1.8.3.jar Security
jarsigner -keystore Security.store ../lib/util/servlet-api.jar Security
jarsigner -keystore Security.store ../lib/util/slf4j-api-1.6.0.jar Security
jarsigner -keystore Security.store ../lib/util/slf4j-log4j12-1.6.0.jar Security